### PR TITLE
Service activity dia

### PR DESCRIPTION
**Pull request by schurch82**
Activity Diagram for Service provider use case. Please review and if good will merge

### CODE REVIEW

**Review by BenhamHosein — APPROVED** [review]
Looks very good

**Comment by rldevries** [comment]
Just wanted to let you know, am looking at it now!

**Comment by schurch82** [comment]
Cool, just realized I forgot to send a msg on slack notifying you that the pull request was up. Let me know if you think it's good to go as well as the other pull requests

**Review by rldevries — APPROVED** [review]
Very clean diagram - G2G!

**Pull request merged**
